### PR TITLE
Fix segfault in pool_createwhatprovides()

### LINKED ISSUE #73: Segfault on current master
```
$ git show
commit 9cb602f2bdb505644f414f92d940c60626a00e84 (HEAD -> master, origin/master, origin/HEAD)
$ meson . builddir
$ ninja -C builddir
$ valgrind ./builddir/fus --platform el8 foo
==12222== Memcheck, a memory error detector
==12222== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==12222== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==12222== Command: ./builddir/fus --platform el8 foo
==12222== 
==12222== Invalid read of size 4
==12222==    at 0x404ED9: pool_whatprovides (pool.h:334)
==12222==    by 0x404F72: pool_whatprovides_ptr (pool.h:348)
==12222==    by 0x405C3F: _repo_add_modulemd_defaults (repo.c:305)
==12222==    by 0x40717E: add_platform_module (repo.c:824)
==12222==    by 0x4071E0: create_system_repo (repo.c:832)
==12222==    by 0x4096A9: fus_depsolve (fus.c:699)
==12222==    by 0x409DD0: main (main.c:69)
==12222==  Address 0x334 is not stack'd, malloc'd or (recently) free'd
==12222== 
==12222== 
==12222== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==12222==  Access not within mapped region at address 0x334
==12222==    at 0x404ED9: pool_whatprovides (pool.h:334)
==12222==    by 0x404F72: pool_whatprovides_ptr (pool.h:348)
==12222==    by 0x405C3F: _repo_add_modulemd_defaults (repo.c:305)
==12222==    by 0x40717E: add_platform_module (repo.c:824)
==12222==    by 0x4071E0: create_system_repo (repo.c:832)
==12222==    by 0x4096A9: fus_depsolve (fus.c:699)
==12222==    by 0x409DD0: main (main.c:69)
==12222==  If you believe this happened as a result of a stack
==12222==  overflow in your program's main thread (unlikely but
==12222==  possible), you can try to increase the size of the
==12222==  main thread stack using the --main-stacksize= flag.
==12222==  The main thread stack size used in this run was 8388608.
==12222== 
==12222== HEAP SUMMARY:
==12222==     in use at exit: 251,587 bytes in 843 blocks
==12222==   total heap usage: 1,163 allocs, 320 frees, 349,526 bytes allocated
==12222== 
==12222== LEAK SUMMARY:
==12222==    definitely lost: 0 bytes in 0 blocks
==12222==    indirectly lost: 0 bytes in 0 blocks
==12222==      possibly lost: 1,544 bytes in 20 blocks
==12222==    still reachable: 242,123 bytes in 764 blocks
==12222==                       of which reachable via heuristic:
==12222==                         length64           : 384 bytes in 9 blocks
==12222==                         newarray           : 1,600 bytes in 20 blocks
==12222==         suppressed: 0 bytes in 0 blocks
==12222== Rerun with --leak-check=full to see details of leaked memory
==12222== 
==12222== For lists of detected and suppressed errors, rerun with: -s
==12222== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped [obraz paměti uložen])
```

### PR DESCRIPTION
**Pull request by lubomir**
When creating defaults for platform, calling the function without first generating the platform provides will result in a crash.

Fixes: #73

### CODE REVIEW

**Review by r4f4 — APPROVED** [review]
+1

File: repo.c [hunk 1]
```diff
@@ -818,6 +818,8 @@ add_platform_module (const char *platform,
   modulemd_module_stream_set_context (module, "00000000");
   modulemd_module_stream_v2_set_arch ((ModulemdModuleStreamV2 *) module, arch);
   add_module_solvables (system, module);
+  /* Required for adding defaults */
+  pool_createwhatprovides (system->pool);
```
Comment (igor-raits) [inline repo.c]: as wrote in the issue, I think it should be in the different function than here.

Comment (lubomir) [reply repo.c]: Should it be called on `pool` or `system->pool`? Both seem to work, but I would expect one to be better.

Comment (r4f4) [reply repo.c]: In `create_system_repo` you can call it with `pool` directly imho.

**Comment by r4f4** [comment]
Thank you for the fix!
